version: '2'
services:
  jupyter:
    image: yuifu/datascience-notebook-millefy:c88678a1c7c9-v0.1.4
    environment:
      JUPYTER_ENABLE_LAB: 1
    ports:
      - 4649:8888
    volumes:
      - ./:/home/jovyan/work
      - ../test_data:/home/jovyan/test_data
    command: start-notebook.sh --NotebookApp.token=''
