version: '2'
services:
  jupyter:
    image: yuifu/datascience-notebook-millefy:7a0c7325e470-v0.1.9
    environment:
      JUPYTER_ENABLE_LAB: 1
    ports:
      - 4649:8888
    volumes:
      - ./:/home/jovyan/work
      - ../test_data:/home/jovyan/test_data
      - ../examples:/home/jovyan/examples
    command: start-notebook.sh --NotebookApp.token=''
