version: '2'
services:
  jupyter:
    image: yuifu/datascience-notebook-millefy:c88678a1c7c9-v0.1.8
    container_name: harukao_datascience_notebook_millefy_00
    environment:
      JUPYTER_ENABLE_LAB: 1
      NB_UID: 10011
      GRANT_SUDO: "yes"
    user: root
    ports:
      - 4649:8888
    volumes:
      - ./:/home/jovyan/work
      - ../test_data:/home/jovyan/test_data
      - ../examples:/home/jovyan/examples
    command: start-notebook.sh --NotebookApp.token=''

